name: Build and Push Container Image
on:
  push:
    branches:
      - main

jobs:
  publish-docker:
    name: Publish Docker Image
    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          # Checkout branch which triggered the action
          ref: ${{ github.ref }}

      - name: Generate image tags
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/extrange/sqlite-deadlock
          tags: |
            type=edge
            type=sha

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          # Build context
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}